path: /Users/dayanbattulga/Desktop/personal-code/projects/waste_vision/data/sortwaste/yolo_4class
train: train/images
val: val/images
test: test/images

names:
  0: PET
  1: HDPE
  2: Mixed_Plastic
  3: ECAL
